version: "2"
services:

  mysql:
    image: mysql:latest
    container_name: 'mysql'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: 'zipkin'
    ports:
      - 9411:9411

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: 'otel-collector'
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./output:/etc/output:rw # Store the logs
    ports:
      - 8888:8888   # Prometheus metrics exposed by the collector
      - 8889:8889   # Prometheus exporter metrics
      - 4317:4317   # OTLP gRPC receiver
    depends_on:
      - zipkin

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672

  redis:
    image: redis:latest
    container_name: 'redis'
    ports:
      - 6022:6379
     