name: Build and test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dotnet 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.403

    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
