name: Publish to nuget
on:
  push:
    branches:
      - publish

jobs:
  publish:
    runs-on: windows-latest
    environment: prod
    permissions:
      id-token: write
      contents: write
    steps:
    - name: ASP.NET environment
      run: echo "${{ secrets.VAR_ENVIRONMENT }}"
    - name: AWS EBS environment
      run: echo "${{ secrets.VAR_EBSENV }}"
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-region: us-east-2
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: GithubActionsNtFreXBlogDelpoyment
    
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.403
    
    - name: Deploy web app
      run: ./deploy/build_and_deploy_web.ps1
    - name: Deploy cert renewal container
      run: ./deploy/build_and_publish_cert_renewal.ps1