name: Publish to nuget
on:
  push:
    branches:
      - publish

jobs:
  publish:
    runs-on: windows-latest    
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-2
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
    
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.403
    
    - name: Deploy web app
      run: ./deploy/build_and_deploy_web.ps1
    - name: Deploy cert renewal container
      run: ./deploy/build_and_publish_cert_renewal.ps1