name: Publish to nuget
on:
  push:
    branches:
      - dev/publish

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.403
    - run: |
          ./deploy/build_and_deploy_web.ps1
